### ISSUE TITLE
JSON invalid when JSON is incomplete due to 32766 characters limit

### ISSUE THREAD

**Issue by jardriscoll** [iMicknl/powerbi-botframework-chat-transcripts#345]
Whenever clicking on certain transcripts in my PowerBI dashboard, at certain times I receive an error "Transcript cannot be loaded. Error: JSON invalid." It does not always happen on every transcript, and I am uncertain as to what is causing the error.

**Comment by iMicknl** [comment]
@jardriscoll can you perhaps share the JSON? You can gather the JSON by adding a table or changing this visual to a table visual and copying the value.

If you would like to share this privately, please email me on firstname.lastname@microsoft.com (see my profile).

**Comment by iMicknl** [comment]
The root cause of this issue (JSON invalid) is that the custom visual does not receive the full JSON and thus it cannot parse the JSON contents to a chat visual.

It seems that your original JSON exceeds the 32766 characters, which is the maximum amount of characters of a text column in Power BI. I haven't seen such long conversations (with metadata) in the past, but we did explore ways to split the text over multiple columns and [concatenate it to one field via DAX](https://www.inkeysolutions.com/blogs/power-bi-how-to-deal-with-a-text-column-having-a-length-of-more-than-32766-characters/) to overcome Power BI field limitations.

Would be good to investigate if this can be a solution. I will add a more clear error message for this specific issue.

@jardriscoll how did you gather the full JSON (which you shared via email)? Via Power BI or via the original source?

**Comment by jardriscoll** [comment]
Hi Mick, I replied back via email. Thank you!

**Comment by jardriscoll** [comment]
Hi Mick, I replied back via email. Thank you!

**Comment by iMicknl** [comment]
Improved the error message in the latest version, thanks for reporting!
