### ISSUE TITLE
Date is always January 19

### ISSUE THREAD

**Issue by SSSTREDDD** [iMicknl/powerbi-botframework-chat-transcripts#67]
All transcripts have the month as January and the incorrect day and time.
![image](https://user-images.githubusercontent.com/28159451/133275142-996838dc-0278-44ea-bc6b-17768172a647.png)

**Comment by iMicknl** [comment]
Thank you for reporting, @SSSTREDDD. I will have a look at this. Could you verify that all dates on the right side are correct?

Could you download the latest release of this custom visual [here](https://github.com/iMicknl/powerbi-botframework-chat-transcripts/releases) and add this to the report? It seems that you are using the Custom Analytics report and this is not using the latest version yet.

**Comment by iMicknl** [comment]
That's a good observation, this would definitely be the same issue, however the screenshot is from an early release version. 😀. I will investigate this!

Which channel are you using on Power Virtual Agents? (e.g. WebChat / Teams / Omnichannel)

**Comment by iMicknl** [comment]
@SSSTREDDD, could you give https://github.com/iMicknl/powerbi-botframework-chat-transcripts/suites/3826403466/artifacts/94732656 a try? This beta build is generated by the pipeline of https://github.com/iMicknl/powerbi-botframework-chat-transcripts/pull/73.

Do you have any specific requests? Like specifying a custom date time format, or adapting the date time to a time zone. It would be good to learn more about how this is used and what is currently lacking.

**Comment by iMicknl** [comment]
@SSSTREDDD this should be fixed in 0.8.0, https://github.com/iMicknl/powerbi-botframework-chat-transcripts/releases.

If you have any other specific requests, e.g. specifying a custom date time format (24h?) or adapting the date time to a time zone, let me know.

**Comment by SSSTREDDD** [comment]
@iMicknl Missed your messages. Thank you for looking into this! I will apply and test when I can. Thanks again.

**Comment by yoalto** [comment]
> SSSTREDDD this should be fixed in 0.8.0, https://github.com/iMicknl/powerbi-botframework-chat-transcripts/releases.
> 
> If you have any other specific requests, e.g. specifying a custom date time format (24h?) or adapting the date time to a time zone, let me know.

Thank you, this was indeed fixed in 0.8.0. (I work with SSSTREDDD)
There are some other display issues in relation to time that I would like to see changed:
- As you've mentioned, adapting the date/time to the local time zone is beneficial, as the time/date in the transcript doesn't match the conversation date field in the table from CDS:
![image](https://user-images.githubusercontent.com/95879848/145614057-6bd386bf-8332-4092-9fd6-41793424a537.png)

- The other display issue I am seeing is that the transcript viewer shows "Yesterday" as the timestamp when the conversation time is actually 2 days ago, due to the time zone issue. I prefer to see the actual timestamp of messages sent/received, instead of simply "Yesterday".
The following image shows my system time, along with the conversation time in the table (2 day difference) yet displaying Yesterday in the transcript viewer.
![image](https://user-images.githubusercontent.com/95879848/145615003-98d86f70-1a81-47bd-badb-722c8ff3d4e3.png)

**Comment by iMicknl** [comment]
Could you perhaps create a new issue for your feature request? (or even split per feature).

Regarding your time issue, there was an issue with the Custom Analytics report that you use, where the `Conversation date` listed in the table wasn't the correct date. You can temporary download the version from here: https://github.com/microsoft/PowerVirtualAgentsSamples/pull/64, to test if this solves your issue around time mismatch.
